name: Build and Deploy
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 23 * * 4'
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install eleventy
        run: npm install -g @11ty/eleventy --unsafe-perm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: eleventy --input=. --output=_site
        env:
          FLAG: ${{ secrets.FLAG }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
